/robot2/controller_manager:
  ros__parameters:
    update_rate: 500
    # ... (sama persis dengan robot1, cuma path-nya /robot2/controller_manager)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    io_and_status_controller:
      type: ur_controllers/GPIOController
    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster
    # force_torque_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

      sensor_name: robot2_tcp_fts_sensor

      interface_names:
        - force.x
        - force.y
        - force.z
        - torque.x
        - torque.y
        - torque.z

      frame_id: robot1_tool0
    tcp_pose_broadcaster:
      type: ur_controllers/TCPPoseBroadcaster
    ur_configuration_controller:
      type: ur_controllers/URConfigurationController
    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    forward_position_controller:
      type: position_controllers/JointGroupPositionController
    forward_effort_controller:
      type: effort_controllers/JointGroupEffortController
    force_mode_controller:
      type: ur_controllers/ForceModeController
    passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController
    freedrive_mode_controller:
      type: ur_controllers/FreedriveModeController
    tool_contact_controller:
      type: ur_controllers/ToolContactController